- name: Create Group, User and Deploy the Public Key
  hosts: all
  become: true
  
  tasks:
# Create group
  - name: Create Groups
    group:
      name: "{{ item }}"
    with_items:
      - devops1
      - devops2

# Create user
  - name: Add several users
    user:
      name: "{{ item.name }}"
      groups: "{{ item.group }}"
      state: present
    with_items: 
      - name: serdem
        group: devops1


# Set autrorized key from file
  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', '/home/{{ item }}/.ssh/id_rsa.pub') }}"
    with_items: 
      - serdem