- name: Create Group, User and Deploy the Public Key
  hosts: all
  become: true
  vars:
    group_name:
    - name: devops1
    - name: devops2
    users:
    - name: serdem
      group: devops1
    - name: deniz
      group: devops2
      
  tasks:
# Create devops group
  - name: Create Groups
    group:
      name: "{{ item.name }}"
    with_items: "{{ group_name }}"

# Create user
  - name: Add several users
    user:
      name: "{{ item.name }}"
      groups: "{{ item.group }}"
      state: present
    with_items: 
      - "{{ users }}"


# Set autrorized key from file
#  - name: Set authorized key taken from file
#    authorized_key:
#      user: "{{ item.name }}"
#      state: present
#      key: "{{ lookup('file', '/home/{{ item.name }}/.ssh/id_rsa.pub') }}"
#    with_items: 
#      - "{{ key_user }}"