- name: Create Group, User and Deploy the Public Key
  hosts: all
  become: true
  vars:
    group_name:
    - name: devops1

  vars_files:
    - ./vars/users_vars.yml
    - ./vars/key_user_vars.yml
      
  tasks:
# Create devops group
  - name: Create Groups
    group:
      name: "{{ item.name }}"
    with_items: "{{ group_name }}"

# Create users and add to group 
  - name: Add several users
    user:
      name: "{{ item.name }}"
      group: "{{ item.group }}"
      state: present
    with_items: 
      - "{{ users }}"


# Set authorize key from file
  - name: Set authorize keys taken from file
    authorized_key:
      user: "{{ item.name }}"
      state: present
      key: "{{ lookup('file', '/home/{{ item.name }}/.ssh/id_rsa.pub') }}"
    with_items: 
      - "{{ key_user }}"